### PR TITLE
Issue #232

### LINKED ISSUE #232: Send transaction not working
**Describe the bug**
Currently when trying to submit a new "MsgSend" transaction with valid credentials we get the following error from the transaction which is not being parsed correctly:

`{"codespace":"sdk","code":4,"message":"signature verification failed; verify correct account sequence and chain-id"}`

And instead of returning a `RpcError`, we are returning the `RawTxResponse`.

**To Reproduce**
1. Create a transaction sender with a valid Private Key: `const txSender = pocket.withPrivateKey(privateKey)`
2. Submit the transaction: `const txResponse = await txSender.send(fromAddress, toAddress, amount).submit(chainId, feeAmount)`

**Expected behavior**
A valid `RawTxResponse` as a response with logs indicating the success.

**Additional context**
This might be related with the transaction bytes that are being sent not being properly encoded in the Amino format.

### PR DESCRIPTION
**Pull request by pabelnl**
Closes #232

### CODE REVIEW

File: src/transactions/i-transaction-sender.ts [hunk 1]
```diff
@@ -21,7 +20,6 @@ export interface ITransactionSender {
     submit(
         chainId: string,
```
Comment (nymd) [inline src/transactions/i-transaction-sender.ts]: The file rpc/models/block-header.ts uses the camelcase of "chainID" instead of "chainId"

I personally prefer chainID but I'm fine either way as long as we are consistent everywhere.

File: src/transactions/models/std-sign-doc.ts [hunk 2]
```diff
@@ -18,13 +18,13 @@ export class StdSignDoc implements IAminoEncodable{
     /**
      * Constructor for the StdSignDoc class
      * @throws {Error} Throws an error if the msgs list is empty or the fee is not a number
-     * @param {BigInt} entropy - Random int64.
```
Comment (nymd) [inline src/transactions/models/std-sign-doc.ts:21]: For my benefit, why is this changed to a string?  Can we add a comment there as to why so the next noob like me isn't confused why an int64 is stored as a string, thanks.

**Review by nymd — CHANGES_REQUESTED** [review]
No real changes requested, just some clarification and comments, thanks.

File: src/transactions/models/std-sign-doc.ts (hunk 2 above)
Comment (pabelnl) [reply src/transactions/models/std-sign-doc.ts:21]: the transaction-sender doesn't receive the entropy as a param anymore, it is always generated, but we changed to string because of some issues while calling the marshalPosmintTx that is related to the amino-js dependency, it wasn't accepting the BigInt, only numbers, and strings. We can safely save a BigInt number representation inside a string, the library works fine with it.

**Review by luyzdeleon — APPROVED** [review]

**Review by nymd — APPROVED** [review]
