### PR TITLE
Issue #271

### LINKED ISSUE #280: Staking/Unstaking/Unjailing not working
**Describe the bug**
Whenever trying to submit a valid Staking/Unstaking/Unjailing transaction, we get hit with an `invalid signature` error.

**To Reproduce**
Create a `TransactionSender` and try to submit any of the aforementioned transactions.

**Expected behavior**
For valid transactions to be accepted.

### PR DESCRIPTION
**Pull request by pabelnl**
closes #280 #279 #271

### CODE REVIEW

File: src/pocket.ts [hunk 1]
```diff
@@ -15,6 +15,16 @@ import { ChallengeRequest } from "./rpc/models/input/challenge-request"
 import { ChallengeResponse } from "./rpc/models/output/challenge-response"
 import { RelayMeta } from "./rpc/models/input/relay-meta"
 
+/**
+ *
+ * HttpMethod enum with the possible Staking status values
+ */
+export enum HttpMethod {
+  POST = "POST",
```
Comment (wgarcia4190) [inline src/pocket.ts:23]: Please add DELETE, the Algorand SDK needs this method

**Review by wgarcia4190 — CHANGES_REQUESTED** [review]

File: src/rpc/providers/pocket-rpc-provider.ts [hunk 2]
```diff
@@ -1,7 +1,7 @@
 import { IRPCProvider } from "./i-rpc-provider"
 import { RpcError } from "../errors"
 import { typeGuard } from "../../utils/type-guard"
-import { Pocket, PocketAAT } from "../../pocket"
+import { Pocket, PocketAAT, HttpMethod } from "../../pocket"
```
Comment (nymd) [inline src/rpc/providers/pocket-rpc-provider.ts]: The capitalization of our UpperCamelCase here is off.

line 1 "IRPCProvider"
line 2 "RpcError"
line 4 "HttpMethod"

If I had to choose, I prefer all caps in first word when appropriate:

"RPCError"
"HTTPMethod"

etc

**Review by nymd — CHANGES_REQUESTED** [review]
Will wait for Wilson's necessary change before approving, thanks

**Review by nymd — APPROVED** [review]

**Review by wgarcia4190 — APPROVED** [review]

**Review by luyzdeleon — APPROVED** [review]
